import os
import atexit
import shutil
import tempfile
from pathlib import Path

os.environ["LLM_MOCK_MODE"] = "true"
os.environ["COMFYUI_MOCK_MODE"] = "true"
os.environ["RENDER_BACKEND"] = "comfyui"

TEST_DATA_DIR = Path(tempfile.mkdtemp(prefix="movie-agent-tests-"))
os.environ["DATA_DIR"] = str(TEST_DATA_DIR)
os.environ["SQLITE_DB_PATH"] = str(TEST_DATA_DIR / "movie_agent.db")
atexit.register(shutil.rmtree, TEST_DATA_DIR, ignore_errors=True)

import subprocess
import pytest

@pytest.fixture(scope="session")
def reference_bytes():
    path = TEST_DATA_DIR / "reference.png"
    subprocess.run(["ffmpeg", "-v", "error", "-y", "-f", "lavfi", "-i", "color=c=blue:size=32x32", "-frames:v", "1", str(path)], check=True)
    return path.read_bytes()


async def bind_reference(service, pid, data):
    from agent.media import AssetMetadata
    asset = await service.register_asset(pid, data, AssetMetadata(purpose="reference", source="Explicit synthetic test image", rights="confirmed", license_note="Generated by this test"))
    for shot in service.get_shots(pid):
        service.update_shot(pid, shot["shot_id"], {"reference_asset_ids": [asset["id"]]})
    await service.compile_packages(pid)
    return asset
